/* Generated by Cython 0.25.2 */

#ifndef __PYX_HAVE__calc_winrate
#define __PYX_HAVE__calc_winrate


#ifndef __PYX_HAVE_API__calc_winrate

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(float) calc(PyObject *, PyObject *, PyObject *, PyObject *, PyObject *, int __pyx_skip_dispatch);

#endif /* !__PYX_HAVE_API__calc_winrate */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcalc_winrate(void);
#else
PyMODINIT_FUNC PyInit_calc_winrate(void);
#endif

#endif /* !__PYX_HAVE__calc_winrate */
